package org.wakeup.domain;

import javax.persistence.*;
import java.util.Objects;

/**
 * Generated by wakeup generator 'http://wakeup.org.in'
 * Hello entity
 */
@Entity
@Table(name = "hello")
public class Hello {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "message")
    private String message;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) { return true; }
        if (o == null || getClass() != o.getClass()) { return false; }
        Hello hello = (Hello) o;
        if ( ! Objects.equals(id, hello.id)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "Emp{" +
                "id=" + id +
                ", message='" + message + "'" +
                '}';
    }
}
