package org.wakeup;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * Generated by wakeup generator 'http://wakeup.org.in'
 * Application
 */
@Controller
@SpringBootApplication
public class Application {

  @RequestMapping("/")
  public String index() { return "index.html"; }

  public static void main(String[] args) {
    SpringApplication app=new SpringApplication(Application.class);
    app.run(args);
  }
}
